COVID_19Analyse/urls.py
from django.urls import path,include

from .views.FileDownload import FileDownload as Down
from .views import UpdateView as Update
from .views import views

app_name = 'covid19'
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path('download/', Down.download_file, name="download"),
    path('maincountry/', views.maincountry, name="maincountry"),
    path('continent/', views.continent, name="continent"),
    path('rank/', views.rank, name="rank"),
    path('trend/', views.trend, name="trend"),
    path("all/", views.covidindex, name="all"),
    path('update/', Update.update, name='update'),
    path('details/<country>', views.details, name='details'),

    # 二级路由 api 数据接口
    path('api/', include('COVID_19Analyse.views.DataImpl.urls')),
]

COVID_19Analyse/views/DataImpl/urls.py
from django.urls import path

from .api import confirmAmplification as Confirm
from .api import overseaTrend as Trend
from .api import rank as Rank
from .api import today as Today
from .api import details as Details
from .api import summarize as Sum

app_name = 'api'
urlpatterns = [
    path('details/',Details.getCountryDetails,name='details'),
    path('sumdetails/',Details.getSumDetails,name='sumdetails'),
    path('mainCountry/',Details.getMainCountryDetails,name='mainCountry'),
    path('oversea/',Confirm.overseaConfirm,name='oversea'),
    path('plc/',Confirm.peopleLargeCountryConfirm,name='plc'),
    path('continent/',Confirm.continentConfirm,name='continent'),
    path('trend/',Trend.getOverseaTrend,name='trend'),
    path('deadrank/', Rank.getDeadRank, name='deadRank'),
    path('healrank/', Rank.getHealRank, name='healRank'),
    path('confirmrank/', Rank.getConfirmRank, name='confirmRank'),
    path('confirmrate/',Rank.getconfirmAmpl,name='confirmRate'),
    path('sum/',Sum.getSummarize,name='sum'),
    path('today/',Today.getToday,name='today'),
]

Web/urls.py
from django.contrib import admin
from django.urls import path,include

from login import views
from COVID_19Analyse.views import views as covid
urlpatterns = [
    # 一级路由
    path('', covid.index),
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),


    # 二级路由
    path('data/', include('COVID_19Analyse.urls')),

]

COVID_19Analyse/models.py
from django.db import models


# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=20, unique=True)
    continent = models.CharField(max_length=5, default="亚洲")

    def __str__(self):
        return self.name

    class Meta:
        indexes = [models.Index(fields=['continent']), ]


class CountryData(models.Model):
    date = models.DateField()
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default="")
    confirm_add = models.IntegerField(default=0)
    confirm = models.IntegerField(default=0)
    heal = models.IntegerField(default=0)
    dead = models.IntegerField(default=0)

    def __str__(self):
        return str(self.country) + " " + self.date.strftime("%Y/%m/%d")

    class Meta:
        indexes = [models.Index(fields=['country']),models.Index(fields=['date']),models.Index(fields=['country','date']), ]

COVID_19Analyse/views/UpdateView.py
# 更新整体数据
from django.contrib.auth.decorators import login_required

from COVID_19Analyse.models import CountryData


@login_required
def update(request):
    from django.http import HttpResponse
    from django.shortcuts import render

    from ..models import Country
    from ..tools.DataSpider import DataSpider
    from ..tools.datetimeSupport import TimeTools
    if request.method == "POST":
        print("----------------更新全部数据----------------")
        # 爬取数据
        spider = DataSpider()

        # 获取国家列表
        countryList = spider.getCountryList()
        for country in countryList:
            print(country['name'])
            try:
                Country.objects.get(name=country['name'])
            except Exception as e:
                # 没有该数据,保存之
                countryObject = Country(name=country['name'],continent=country['continent'])
                countryObject.save()


        # 获取国家列表
        countries = Country.objects.all()
        countryDateDictList = []
        # 设置开始时间
        for country in countries:
            dictTmp = {country.name: TimeTools.getBegin()}
            countryDateDictList.append(dictTmp)
        Timelist = TimeTools.getGapTime(TimeTools.getBegin())
        Timedict = {}
        for timeTmp in Timelist:
            Timedict[timeTmp] = 0


        ans = spider.update(countryDateDictList)

        for key in ans:
            print(key)
            countryObject = Country.objects.get(name=key)
            for data in ans[key]:
                try:
                    dataObject = countryObject.countrydata_set.get(date=data["date"])
                except Exception as e:
                    dataObject = CountryData(date=data["date"], country=countryObject)
                Timedict[data["date"]] += 1
                dataObject.confirm_add = data["confirm_add"]
                dataObject.confirm = data["confirm"]
                dataObject.heal = data["heal"]
                dataObject.dead = data["dead"]

                dataObject.save()
        for timeTmp in Timedict:
            print("{:<12} {}条数据已更新".format(timeTmp.strftime("%Y-%m-%d"), Timedict[timeTmp]))
        print("-----------------更新结束-----------------")
        print()

        return HttpResponse("刷新成功", status=200)
    else:
        return render(request, "COVID_19Analyse/update.html")

COVID_19Analyse/views/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'COVID_19Analyse/index.html')

@login_required
def covidindex(request):
    return render(request, 'COVID_19Analyse/main.html')

@login_required
def dashboard(request):
    context = {'username': request.user.username}
    return render(request, 'COVID_19Analyse/Dashboard.html',context)

@login_required
def rank(request):
    context = {'username': request.user.username}
    return render(request, 'COVID_19Analyse/Rank.html',context)

@login_required
def trend(request):
    context = {'username': request.user.username}
    return render(request, 'COVID_19Analyse/Trend.html',context)

@login_required
def maincountry(request):
    context = {'username': request.user.username}
    return render(request, 'COVID_19Analyse/MainCountry.html',context)

@login_required
def continent(request):
    context = {'username': request.user.username}
    return render(request, 'COVID_19Analyse/Continent.html',context)

@login_required
def details(request,country):
    context = {'username': request.user.username,'country':country}
    return render(request, 'COVID_19Analyse/details.html',context)

COVID_19Analyse/templates/COVID_19Analyse/data.html
{% load static %}
<!DOCTYPE html>
<html style="height: 100%">
<head>
    <meta charset="utf-8">
    <link REL="SHORTCUT ICON" HREF="{% static "favicon.ico" %}"/>
</head>
<body style="height: 100%; margin: 0;text-align: center">


<div id="container" style="margin:0 auto;width:50%;height: 60%;">

</div>

<form action="/add/" method="get" id="Iform">
    {% csrf_token %}
    <input type="text" name="country" id="country">
    <br>
    <button type="button" id='click'>提交</button>
</form>


<script src={% static "COVID_19Analyse/jss/jquery.min.js" %}></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts-gl/dist/echarts-gl.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts-stat/dist/ecStat.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/extension/dataTool.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/map/js/china.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/map/js/world.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/extension/bmap.min.js"></script>
<script src="{% static 'COVID_19Analyse/js/theme.js' %}"></script>
<script src="{% static 'COVID_19Analyse/js/CensusCountry.js' %}"></script>


<script>
    $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
    });

    $("#click").click(function () {
        $.ajax({
            url: "{% url 'Analyse:getLastMonthDataByCountry'%}",
            type: "POST",
            data: $("#Iform").serialize(),
            success: function (data) {
                str = "";
                console.log(data);
                $("#result").html("");
                var date = Array();
                var confirm_add = Array();
                var confirm = Array();
                var dead = Array();
                var heal = Array();
                $.each(data, function (i, tmp) {
                    date.push(tmp.date);
                    confirm_add.push(tmp.confirm_add);
                    dead.push(tmp.dead);
                    heal.push(tmp.heal);
                    confirm.push(tmp.confirm - tmp.heal - tmp.dead);
                });
                var datas = Array();
                datas[0] = date.reverse();
                console.log(typeof date[1]);
                datas[1] = confirm.reverse();
                datas[2] = heal.reverse();
                datas[3] = dead.reverse();
                datas[0].unshift("情况");
                datas[1].unshift("确诊人数");
                datas[2].unshift("治愈人数");
                datas[3].unshift("死亡人数");
                console.log(datas);
                b = datas[0][1];
                show("container", datas, b);

            }
        });
    });
</script>
</body>
</html>

COVID_19Analyse/templates/COVID_19Analyse/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'covid19:update' %}" method="post">
    {% csrf_token %}
    <button>更新</button>
</form>
</body>
</html>